stages:
  - deploy

deploy:
  stage: deploy to kubernetes
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
  - kubectl config use-context $CONTEXT
  - |
    eval "cat << EOF       
    $(cat manifests/*.yaml)
    EOF" | kubectl apply -f -
    