stages:
  - build
  - test
  - deploy



docker-build:
  image: docker:latest
  stage: build
  ######################
   # rules:
   #  - when: never
   #####################
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_BUILDKIT=1
    - export COMPOSE_DOCKER_CLI_BUILD=1
  script:
    # test build nginx-1
    # - docker build -t $CI_REGISTRY_IMAGE:"nginx-1-"$CI_COMMIT_SHORT_SHA ./nginx-test
    # - docker push $CI_REGISTRY_IMAGE:"nginx-1-"$CI_COMMIT_SHORT_SHA

    # build backend
    - docker build -t $CI_REGISTRY_IMAGE:"backend-"$CI_COMMIT_SHORT_SHA ./backend
    - docker push $CI_REGISTRY_IMAGE:"backend-"$CI_COMMIT_SHORT_SHA

    # build frontend
    - docker build -t $CI_REGISTRY_IMAGE:"frontend-"$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE:"frontend-"$CI_COMMIT_SHORT_SHA

  # allow_failure: true



docker-test:
  stage: test
  ######################
  # rules:
  #  - when: never
  #####################
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # test pull nginx-1
    # - docker pull $CI_REGISTRY_IMAGE:nginx-1-$CI_COMMIT_SHORT_SHA

    # test pull backend
    - docker pull $CI_REGISTRY_IMAGE:backend-$CI_COMMIT_SHORT_SHA

    # test pull frontend
    - docker pull $CI_REGISTRY_IMAGE:frontend-$CI_COMMIT_SHORT_SHA

deploy-to-kuber:
  stage: deploy
  ######################
  # rules:
  #   - when: never
  #####################
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config set-cluster k8s --server=$KUBER_URL --insecure-skip-tls-verify=true
    - kubectl config set-credentials $KUBER_USER --token=$KUBER_TOKEN
    - kubectl config set-context default --cluster=k8s --user=$KUBER_USER
    - kubectl config use-context default
    
    # delete docker-registry secret
    - kubectl delete secret regcred -n $KUBER_NAMESPACE

    # create docker-registry secret
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_REGISTRY_PASSWORD --docker-email="test@test.test"  -n $KUBER_NAMESPACE
    # - |
    #   eval "cat << EOF       
    #   $(cat manifests/*.yaml)
    #   EOF" | kubectl apply -f -
    - kubectl apply -f ./manifests/backend.yaml
    - kubectl apply -f ./manifests/frontend.yaml
    # - kubectl apply -f ./manifests/nginx_test_2.yaml