apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: $KUBER_NAMESPACE
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
