apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: ""
    namespace: $KUBER_NAMESPACE
spec:
    issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt
    dnsNames:
        - ""
    secretName: ""
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ""
    namespace: $KUBER_NAMESPACE
    annotations:
        cert-manager.io/clusterissuer: letsencrypt
        kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - ..
      secretName: ""
  rules:
    - host: ""
      http:
        paths:
