apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: $KUBER_NAMESPACE
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: $CI_REGISTRY_IMAGE:frontend-$CI_COMMIT_SHORT_SHA
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred