version: '3.9'
services:

  conveyor:
    container_name: cc-conveyor
    build:
      context: conveyor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
#    restart: unless-stopped

  deal:
    container_name: cc-deal
    build:
      context: deal
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_URL=jdbc:postgresql://credit-conveyor-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KAFKA_HOST_NAME=credit-conveyor-kafka:9092
      - CONVEYOR_HOST=http://cc-conveyor:8080/
      - FINISH_REGISTRATION=finish-registration
      - CREATE_DOCUMENTS=create-documents
      - SEND_DOCUMENTS=send-documents
      - SEND_SES=send-ses
      - CREDIT_ISSUED=credit-issued
      - APPLICATION_DENIED=application-denied
#    restart: unless-stopped

  application:
    container_name: cc-application
    build:
      context: application
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - DEAL_HOST=http://cc-deal:8081/
#    restart: unless-stopped

  dossier:
    container_name: cc-dossier
    build:
      context: dossier
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - KAFKA_HOST_NAME=credit-conveyor-kafka:9092
      - DEAL_HOST=http://cc-deal:8081/
      - MAIL_USER_NAME=credit.conveyor.ksu
      - MAIL_PASSWORD=bgipduuoruqonabs
      - FINISH_REGISTRATION=finish-registration
      - CREATE_DOCUMENTS=create-documents
      - SEND_DOCUMENTS=send-documents
      - SEND_SES=send-ses
      - CREDIT_ISSUED=credit-issued
      - APPLICATION_DENIED=application-denied
#    restart: unless-stopped

  gateway:
    container_name: cc-gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - APPLICATION_HOST=http://cc-application:8082/
      - DEAL_HOST=http://cc-deal:8081/
#    restart: unless-stopped


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: credit-conveyor-zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    container_name: credit-conveyor-kafka
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    volumes:
      - credit-conveyor-kafka:/kafka

  postgres:
    container_name: credit-conveyor-db
    image: postgres:alpine3.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - credit-conveyor-data:/var/lib/postgresql/data/

volumes:
  credit-conveyor-kafka:
  credit-conveyor-data: